# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='nome')),
                ('end', models.CharField(blank=True, max_length=20, verbose_name='end')),
                ('tel', models.CharField(blank=True, max_length=20, verbose_name='tel')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=20, verbose_name='serviço')),
                ('valor', models.CharField(blank=True, max_length=20, verbose_name='end')),
                ('id_cliente', models.CharField(blank=True, max_length=20, verbose_name='tel')),
                ('id_veiculo', models.IntegerField(verbose_name='id_veiculos')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ['servico'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='placa')),
                ('tipo', models.CharField(blank=True, max_length=20, verbose_name='tipo')),
                ('modelo', models.CharField(blank=True, max_length=20, verbose_name='modelo')),
                ('id_cliente', models.IntegerField(verbose_name='id_cliente')),
            ],
            options={
                'verbose_name': 'placa',
                'verbose_name_plural': 'placas',
                'ordering': ['placa'],
            },
        ),
    ]
