# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['placa'], 'verbose_name': 'veiculo', 'verbose_name_plural': 'veiculos'},
        ),
        migrations.AlterField(
            model_name='servicos',
            name='id_cliente',
            field=models.IntegerField(verbose_name='id_cliente'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor'),
        ),
    ]
